"""Tests for terraform_pr_generator.py.

Covers:
- Terraform HCL generation for EC2, RDS, and S3
- Risk assessment logic
- GitHub PR creation (mocked)
- Idempotency (no duplicate PRs)
- Branch naming
- Error handling
"""

import json
import os
from unittest.mock import MagicMock, patch, PropertyMock

import pytest

import terraform_pr_generator
from terraform_pr_generator import (
    build_pr_description,
    estimate_change_risk,
    generate_approval_workflow,
    generate_ec2_downsizing_terraform,
    generate_rds_downsizing_terraform,
    generate_s3_lifecycle_terraform,
)


# ---------------------------------------------------------------------------
# Fixtures
# ---------------------------------------------------------------------------

@pytest.fixture
def ec2_recommendation():
    return {
        "instance_id": "i-0abc123",
        "current_type": "m5.xlarge",
        "recommended_type": "t3.large",
        "estimated_savings": 80.0,
        "name": "payment-service-prod",
        "environment": "prod",
    }


@pytest.fixture
def rds_recommendation():
    return {
        "instance_id": "mydb-prod",
        "instance_class": "db.m5.xlarge",
        "recommended_class": "db.t3.large",
        "estimated_savings": 120.0,
        "engine": "mysql",
        "multi_az": True,
    }


@pytest.fixture
def s3_recommendation():
    return {
        "bucket_name": "my-company-logs",
        "unused_storage_gb": 500.0,
        "monthly_savings": 9.50,
    }


# ---------------------------------------------------------------------------
# Risk assessment
# ---------------------------------------------------------------------------

class TestEstimateChangeRisk:
    def test_same_family_ec2_is_low_risk(self):
        risk = estimate_change_risk("ec2", "t3.large", "t3.medium")
        assert risk["risk_level"] == "low"

    def test_cross_family_m5_to_t3_is_medium_risk(self):
        risk = estimate_change_risk("ec2", "m5.xlarge", "t3.large")
        assert risk["risk_level"] == "medium"

    def test_rds_same_family_is_low_risk(self):
        risk = estimate_change_risk("rds", "db.m5.xlarge", "db.m5.large")
        assert risk["risk_level"] == "low"

    def test_lambda_is_always_low_risk(self):
        risk = estimate_change_risk("lambda", "1024", "512")
        assert risk["risk_level"] == "low"
        assert risk["estimated_downtime"] == "0 seconds"

    def test_missing_config_returns_high_risk(self):
        risk = estimate_change_risk("ec2", "", "t3.medium")
        assert risk["risk_level"] == "high"

    def test_unknown_resource_type_returns_high_risk(self):
        risk = estimate_change_risk("elasticache", "cache.r5.large", "cache.t3.medium")
        assert risk["risk_level"] == "high"

    def test_reasoning_is_non_empty(self):
        risk = estimate_change_risk("ec2", "m5.xlarge", "t3.large")
        assert risk["reasoning"]
        assert risk["estimated_downtime"]


# ---------------------------------------------------------------------------
# Terraform HCL generation
# ---------------------------------------------------------------------------

class TestGenerateEc2DownsizingTerraform:
    def test_output_contains_resource_block(self, ec2_recommendation):
        tf = generate_ec2_downsizing_terraform([ec2_recommendation])
        assert 'resource "aws_instance"' in tf

    def test_output_contains_recommended_type(self, ec2_recommendation):
        tf = generate_ec2_downsizing_terraform([ec2_recommendation])
        assert 't3.large' in tf

    def test_output_contains_previous_type_comment(self, ec2_recommendation):
        tf = generate_ec2_downsizing_terraform([ec2_recommendation])
        assert "m5.xlarge" in tf

    def test_output_contains_savings_comment(self, ec2_recommendation):
        tf = generate_ec2_downsizing_terraform([ec2_recommendation])
        assert "$80" in tf or "80.00" in tf

    def test_output_contains_date_header(self, ec2_recommendation):
        tf = generate_ec2_downsizing_terraform([ec2_recommendation])
        assert "Auto-generated by FinOps" in tf

    def test_empty_recommendations_returns_header_only(self):
        tf = generate_ec2_downsizing_terraform([])
        assert "Auto-generated" in tf
        assert 'resource "aws_instance"' not in tf

    def test_multiple_recommendations(self, ec2_recommendation):
        recs = [
            ec2_recommendation,
            {**ec2_recommendation, "instance_id": "i-second", "name": "another-svc"},
        ]
        tf = generate_ec2_downsizing_terraform(recs)
        assert tf.count('resource "aws_instance"') == 2

    def test_lifecycle_block_present(self, ec2_recommendation):
        tf = generate_ec2_downsizing_terraform([ec2_recommendation])
        assert "lifecycle" in tf
        assert "ignore_changes" in tf


class TestGenerateRdsDownsizingTerraform:
    def test_output_contains_rds_resource(self, rds_recommendation):
        tf = generate_rds_downsizing_terraform([rds_recommendation])
        assert 'resource "aws_db_instance"' in tf

    def test_output_contains_apply_immediately_false(self, rds_recommendation):
        tf = generate_rds_downsizing_terraform([rds_recommendation])
        assert "apply_immediately   = false" in tf

    def test_recommended_class_in_output(self, rds_recommendation):
        tf = generate_rds_downsizing_terraform([rds_recommendation])
        assert "db.t3.large" in tf


class TestGenerateS3LifecycleTerraform:
    def test_output_contains_lifecycle_resource(self, s3_recommendation):
        tf = generate_s3_lifecycle_terraform([s3_recommendation])
        assert 'resource "aws_s3_bucket_lifecycle_configuration"' in tf

    def test_glacier_transition_present(self, s3_recommendation):
        tf = generate_s3_lifecycle_terraform([s3_recommendation])
        assert "GLACIER" in tf
        assert "days = 90" in tf

    def test_deep_archive_transition_present(self, s3_recommendation):
        tf = generate_s3_lifecycle_terraform([s3_recommendation])
        assert "DEEP_ARCHIVE" in tf
        assert "180" in tf

    def test_expiration_present(self, s3_recommendation):
        tf = generate_s3_lifecycle_terraform([s3_recommendation])
        assert "days = 365" in tf

    def test_bucket_name_in_output(self, s3_recommendation):
        tf = generate_s3_lifecycle_terraform([s3_recommendation])
        assert "my-company-logs" in tf


# ---------------------------------------------------------------------------
# PR description builder
# ---------------------------------------------------------------------------

class TestBuildPrDescription:
    def test_contains_summary_section(self):
        desc = build_pr_description(
            changes=[{"resource_id": "i-1", "from": "m5.xlarge", "to": "t3.large", "monthly_savings": 80, "risk": "low"}],
            annual_savings=960,
            risk_summary="Low risk overall",
            affected_resources=["i-1"],
        )
        assert "## Summary" in desc
        assert "$960" in desc or "960" in desc

    def test_contains_affected_resources(self):
        desc = build_pr_description(
            changes=[],
            annual_savings=0,
            risk_summary="",
            affected_resources=["i-abc", "i-def"],
        )
        assert "i-abc" in desc
        assert "i-def" in desc

    def test_contains_review_checklist(self):
        desc = build_pr_description(
            changes=[], annual_savings=0, risk_summary="", affected_resources=[]
        )
        assert "Review Checklist" in desc or "Checklist" in desc


# ---------------------------------------------------------------------------
# Approval workflow
# ---------------------------------------------------------------------------

class TestGenerateApprovalWorkflow:
    def test_contains_approve_button(self):
        workflow = generate_approval_workflow(
            pr_url="https://github.com/org/repo/pull/1",
            changes_summary="2 EC2 instances to downsize",
        )
        # Find the actions block which contains the buttons
        actions_block = next(b for b in workflow["blocks"] if b.get("type") == "actions")
        action_ids = [e["action_id"] for e in actions_block["elements"]]
        assert "finops_approve_apply" in action_ids

    def test_contains_reject_button(self):
        workflow = generate_approval_workflow(
            pr_url="https://github.com/org/repo/pull/1",
            changes_summary="Test",
        )
        actions_block = next(b for b in workflow["blocks"] if b.get("type") == "actions")
        action_ids = [e["action_id"] for e in actions_block["elements"]]
        assert "finops_reject" in action_ids

    def test_pr_url_in_message(self):
        pr_url = "https://github.com/org/repo/pull/42"
        workflow = generate_approval_workflow(pr_url=pr_url, changes_summary="x")
        assert pr_url in json.dumps(workflow)

    def test_fallback_text_present(self):
        workflow = generate_approval_workflow(
            pr_url="https://github.com/org/repo/pull/1",
            changes_summary="",
        )
        assert "text" in workflow


# ---------------------------------------------------------------------------
# GitHub PR creation (mocked)
# ---------------------------------------------------------------------------

class TestCommitAndCreateGithubPr:
    def test_missing_github_token_raises(self):
        with patch.dict(os.environ, {"GITHUB_TOKEN": "", "GITHUB_REPO": "org/repo"}):
            with pytest.raises(EnvironmentError, match="GITHUB_TOKEN"):
                terraform_pr_generator.commit_and_create_github_pr(
                    tf_changes={}, title="Test", description="body"
                )

    def test_missing_github_repo_raises(self):
        with patch.dict(os.environ, {"GITHUB_TOKEN": "ghp_test", "GITHUB_REPO": ""}):
            with pytest.raises(EnvironmentError, match="GITHUB_REPO"):
                terraform_pr_generator.commit_and_create_github_pr(
                    tf_changes={}, title="Test", description="body"
                )

    def test_pr_created_successfully(self):
        mock_gh = MagicMock()
        mock_repo = MagicMock()
        mock_branch_ref = MagicMock()
        mock_branch_ref.commit.sha = "abc123"
        mock_repo.get_branch.return_value = mock_branch_ref

        mock_pr = MagicMock()
        mock_pr.html_url = "https://github.com/org/repo/pull/99"
        mock_repo.create_pull.return_value = mock_pr
        mock_repo.get_pulls.return_value = iter([])

        # Simulate file doesn't exist yet
        from github.GithubException import UnknownObjectException
        mock_repo.get_contents.side_effect = UnknownObjectException(404, {}, {})

        mock_gh.get_repo.return_value = mock_repo

        with patch.dict(
            os.environ,
            {"GITHUB_TOKEN": "ghp_test", "GITHUB_REPO": "org/repo", "GITHUB_BRANCH_MAIN": "main"},
        ), patch("terraform_pr_generator.Github", return_value=mock_gh):
            pr_url = terraform_pr_generator.commit_and_create_github_pr(
                tf_changes={"terraform/test.tf": "# content"},
                title="Cost Optimization: Test",
                description="body text",
            )

        assert pr_url == "https://github.com/org/repo/pull/99"
        mock_repo.create_git_ref.assert_called_once()
        mock_repo.create_file.assert_called_once()
        mock_repo.create_pull.assert_called_once()

    def test_existing_pr_skips_creation(self):
        mock_gh = MagicMock()
        mock_repo = MagicMock()

        existing_pr = MagicMock()
        existing_pr.title = "Cost Optimization: Test"
        existing_pr.html_url = "https://github.com/org/repo/pull/5"
        mock_repo.get_pulls.return_value = iter([existing_pr])
        mock_gh.get_repo.return_value = mock_repo

        with patch.dict(
            os.environ,
            {"GITHUB_TOKEN": "ghp_test", "GITHUB_REPO": "org/repo"},
        ), patch("terraform_pr_generator.Github", return_value=mock_gh):
            pr_url = terraform_pr_generator.commit_and_create_github_pr(
                tf_changes={},
                title="Cost Optimization: Test",
                description="body",
            )

        assert pr_url == "https://github.com/org/repo/pull/5"
        mock_repo.create_git_ref.assert_not_called()

    def test_pygithub_not_available_raises_import_error(self):
        with patch.object(terraform_pr_generator, "_GITHUB_AVAILABLE", False):
            with pytest.raises(ImportError, match="PyGithub"):
                terraform_pr_generator.commit_and_create_github_pr(
                    tf_changes={}, title="T", description="D"
                )

    def test_branch_name_matches_expected_pattern(self):
        mock_gh = MagicMock()
        mock_repo = MagicMock()
        mock_repo.get_branch.return_value.commit.sha = "sha1"
        mock_repo.get_pulls.return_value = iter([])

        from github.GithubException import UnknownObjectException
        mock_repo.get_contents.side_effect = UnknownObjectException(404, {}, {})

        mock_pr = MagicMock()
        mock_pr.html_url = "https://github.com/org/repo/pull/10"
        mock_repo.create_pull.return_value = mock_pr
        mock_gh.get_repo.return_value = mock_repo

        created_refs: list[str] = []
        mock_repo.create_git_ref.side_effect = lambda ref, sha: created_refs.append(ref)

        with patch.dict(
            os.environ,
            {"GITHUB_TOKEN": "ghp_test", "GITHUB_REPO": "org/repo"},
        ), patch("terraform_pr_generator.Github", return_value=mock_gh):
            terraform_pr_generator.commit_and_create_github_pr(
                tf_changes={"terraform/t.tf": "# tf"},
                title="PR",
                description="desc",
            )

        assert len(created_refs) == 1
        assert created_refs[0].startswith("refs/heads/auto/cost-optimization-")
